### ISSUE TITLE
Start Spring Application without @ComponentScan

### ISSUE THREAD

**Issue by Richargh** [Richargh/spring-kotlin-hexagonal#1]
I want to follow the guidelines from [„How Fast is Spring“](https://spring.io/blog/2018/12/12/how-fast-is-spring) and move from @Configuration classes to functional bean registration. So far this proves troublesome because I need to supply application.properties somehow and they are not recognized automatically.

[ApplicationPropertiesTest](https://github.com/Richargh/spring-kotlin-hexagonal/blob/master/price/src/test/kotlin/de/richargh/springkotlinhexagonal/ApplicationPropertiesTest.kt) shows the problem. I either need to supply @propertysource (1 test) or @ComponentScan (3rd test). If I don’t no application.properties are found (2nd test).

**Comment by dsyer** [comment]
Definitely, `@ComponentScan` has nothing to do with properties file reading or binding. Your test that is red must be creating the application context in a different way. If I were you I'd try and find out why. I find the Kotlin code a bit hard to grok, so I can't immediately see the difference (if JetBrains can fix the Eclipse support I would be able to take a closer look).

Just so we are clear, with Spring Boot 2.2, there is a diminishing return to the functional bean definitions, so I'm not sure this exercise is worth a lot of effort. Also, you won't see most of the benefit if only your application's own beans are functional - you are still using a`@EnableAutoConfiguration` and the default configuration class parser in Spring Boot.

**Comment by Richargh** [comment]
A month and then some later: thanks to your comment about the `@ComponentScan` and this [article](https://blog.frankel.ch/spring-boot-migrating-functional/) I figured it out. In my production code I need to use the `runApplication<>` Kotlin method. Then it properly loads the application.properties and application-dev.properties. 

I rewrote most of the code, hopefully making it clearer. 

Can you tell me how to replace `@EnableAutoConfiguration`?

**Comment by Richargh** [comment]
Never mind, I found the [solution](https://github.com/dsyer/spring-boot-micro-apps/blob/master/src/main/java/com/example/micro/MicroApplication.java). I think I am waiting for mature Spring Fu :)
